"""VPAX file parser.

Reads .vpax files (generated by DAX Studio or Tabular Editor), which are zip
archives containing a DaxVpaView.json file. We extract column cardinality and size
to enable size-aware rules.
"""

from __future__ import annotations

import json
import zipfile
from pathlib import Path

from coop_dax_review.diagnostics import Diagnostic
from coop_dax_review.model import ModelCatalog, normalize


def load_vpax(vpax_path: str | Path) -> dict[str, dict[str, dict[str, int]]]:
    """Parse a .vpax file and return extracted stats.

    Returns:
        A dict of `normalized_table -> normalized_column -> {"cardinality": int, "size_bytes": int}`.
    """
    path = Path(vpax_path)
    if not path.is_file():
        raise OSError(f"VPAX file not found: {path}")

    try:
        with zipfile.ZipFile(path, "r") as z:
            if "DaxVpaView.json" not in z.namelist():
                raise ValueError("VPAX file does not contain DaxVpaView.json")

            # VPAX json is usually UTF-16 LE encoded, but zipfile read returns bytes.
            raw_bytes = z.read("DaxVpaView.json")
    except zipfile.BadZipFile as exc:
        raise ValueError(f"Invalid VPAX file (not a zip archive): {exc}") from exc

    # Try common encodings
    text = None
    for encoding in ("utf-16-le", "utf-16-be", "utf-8", "utf-8-sig"):
        try:
            text = raw_bytes.decode(encoding)
            if text.startswith("{"):
                break
        except UnicodeDecodeError:
            pass

    if text is None:
        raise ValueError("Could not decode DaxVpaView.json (unknown encoding)")

    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in DaxVpaView.json: {exc}") from exc

    stats: dict[str, dict[str, dict[str, int]]] = {}
    model_data = data.get("Model", {})
    for table in model_data.get("Tables", []):
        t_name = normalize(table.get("TableName", ""))
        t_stats = {}
        for column in table.get("Columns", []):
            c_name = normalize(column.get("ColumnName", ""))
            cardinality = column.get("ColumnCardinality", 0)

            # Sum up sizes: DataSize + DictionarySize
            data_size = column.get("DataSize", 0)
            dict_size = column.get("DictionarySize", 0)
            total_size = data_size + dict_size

            t_stats[c_name] = {
                "cardinality": cardinality,
                "size_bytes": total_size,
            }
        if t_stats:
            stats[t_name] = t_stats

    return stats


def apply_vpax_stats(catalogs: list[ModelCatalog], vpax_path: Path) -> None:
    """Load stats from a VPAX file and apply them to the models in place.

    If the VPAX file is out of sync with the model (missing tables/columns),
    a diagnostic is added to the catalog.
    """
    try:
        stats = load_vpax(vpax_path)
    except (OSError, ValueError) as exc:
        for cat in catalogs:
            cat.diagnostics.append(
                Diagnostic(
                    severity="error",
                    category="vpax_load_error",
                    file=vpax_path.as_posix(),
                    line=0,
                    message=f"Could not load VPAX file: {exc}",
                )
            )
        return

    # To detect staleness, track what we used
    vpax_used_tables: set[str] = set()

    for cat in catalogs:
        stale_messages = []
        for table in cat.tables:
            t_norm = normalize(table.name)
            if t_norm not in stats:
                stale_messages.append(f"table '{table.name}' not found in VPAX")
                continue

            vpax_used_tables.add(t_norm)
            t_stats = stats[t_norm]

            for column in table.columns:
                c_norm = normalize(column.name)
                if c_norm not in t_stats:
                    if not column.is_calculated:
                        # Calculated columns might not be in VPAX depending on export options
                        stale_messages.append(f"column '{table.name}[{column.name}]' not found in VPAX")
                    continue

                c_stats = t_stats[c_norm]
                column.cardinality = c_stats["cardinality"]
                column.size_bytes = c_stats["size_bytes"]

        if stale_messages:
            msg = f"VPAX file may be stale ({len(stale_messages)} mismatches, e.g. {stale_messages[0]})"
            cat.diagnostics.append(
                Diagnostic(
                    severity="warning",
                    category="vpax_stale",
                    file=vpax_path.as_posix(),
                    line=0,
                    message=msg,
                )
            )
